name: finanzas_app
description: Una app de finanzas simple

publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  sqflite: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  excel: ^2.1.0

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
